In [11]:
# !pip install numpy

In [12]:
import numpy as np # numpy written in c

In [13]:
a=[1,23,4.5,3]

In [14]:
np.sum(a)

31.5

In [15]:
a=np.array([1,34,45,67,3])

In [16]:
a

array([ 1, 34, 45, 67,  3])

In [17]:
print(type(a))

<class 'numpy.ndarray'>


In [18]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
l1=[1,2,3,4]

In [23]:
arr=np.array(l1)

In [24]:
type(arr)

numpy.ndarray

In [28]:
arr.shape

(4,)

In [29]:
b.shape

(3, 3)

In [32]:
b.sum()

45

In [33]:
b/2


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [34]:
b*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# speed mesurement 

In [40]:
c=range(1,10)


In [41]:
c

range(1, 10)

In [53]:
%timeit a=[i for i in c]

741 ns ± 9.54 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [54]:
a

array([ 1, 34, 45, 67,  3])

In [55]:
%timeit a_numpy=np.arange(1,10)

1.22 µs ± 16.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [58]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [67]:
np.zeros((1,6)).reshape(2,3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.full((4,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [73]:
np.diag(l1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [74]:
l1

[1, 2, 3, 4]

In [82]:
100*np.random.random()+1

66.70232679426798

In [87]:
100*np.random.random([1,3])+1

array([[52.29598378, 36.08824861, 60.62801614]])

In [92]:
var1=np.linspace(1,100,100)

In [93]:
var1

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [95]:
np.sin(np.pi/2)

1.0

In [96]:
np.exp(3)

20.085536923187668